//: Playground - noun: a place where people can play

import UIKit

var str = "Hello, playground"

//Question: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//Remember the single principle for each function

//calculate all the fibonacci Numbers
func calculateFibonacciNumbers(num: Int) -> [Int] {
    
    var result: Int = 1
    var resultsArray = [Int]()
    
    for i in 1...num {
        result = result + i
        resultsArray.append(result)
    }
    
    return resultsArray
}

func findEvenNumbers (array: [Int]) -> [Int]{

    var returnArray = [Int]()
    
    var limit = 4000000
    
    for num in array{
        if num != limit && num % 2 == 0 {
            returnArray.append(num)
        }
    }

    return returnArray
}

var newArray = calculateFibonacciNumbers(num: 100)

findEvenNumbers(array:newArray)


